name: prod

on:
  push:
    branches:
    - main

jobs:
  devops:
    runs-on: [self-hosted,prod]
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      
      - name: Test Ansible
        run: ansible --version
