name: CloudOps-CTPP

on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Job to run.'
        required: true
        type: choice
        options:
        - all-jobs
        - prometheus-federation
        - haproxy-int-lb
        - alert-manager-setup
        - prometheus-ctpp


env:
  INVENTORY: ./inventory/skt-ctpp-monitoring.ini
  PLAYBOOK: cloudops-ctpp.yaml
  PROM_FED_TAG: gather-facts, prometheus-federation-server
  HAPROXY_TAG: haproxy-int-lb
  ALERTMANAGER_TAG: alert-manager-setup
  PROM_TAG: gather-facts, prometheus-ctpp


jobs:
  prometheus-federation:
    runs-on: ubuntu-latest
    name: Setup prometheus-federation server
    if: ${{ github.event.inputs.job }} == {{ github.job }}
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install ansible package
        run: |-
          sudo apt install --no-install-recommends python-netaddr -y
          pip3 install netaddr     
      
      - name: Run Ansible command
        run: ansible-playbook -i $INVENTORY $PLAYBOOK --tag "$PROM_FED_TAG"

  haproxy-int-lb:
    runs-on: ubuntu-latest
    name: Setup haproxy internal
    if: ${{ github.event.inputs.job }} == {{ github.job }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install ansible package
        run: |-
          sudo apt install --no-install-recommends python-netaddr -y
          pip3 install netaddr
      
      - name: Run Ansible command
        run: ansible-playbook -i $INVENTORY $PLAYBOOK --tag $HAPROXY_TAG

  alert-manager-setup:
    runs-on: ubuntu-latest
    name: Setup Alert Manager
    if: ${{ github.event.inputs.job }} == {{ github.job }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install ansible package
        run: |-
          sudo apt install --no-install-recommends python-netaddr -y
          pip3 install netaddr

      - name: Run Ansible command
        run: ansible-playbook -i $INVENTORY $PLAYBOOK --tag $ALERTMANAGER_TAG

  prometheus-ctpp:
    runs-on: ubuntu-latest
    name: Setup prometheus ctpp
    if: ${{ github.event.inputs.job }} == {{ github.job }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install ansible package
        run: |-
          sudo apt install --no-install-recommends python-netaddr -y
          pip3 install netaddr

      - name: Run Ansible command
        run: ansible-playbook -i $INVENTORY $PLAYBOOK --tag "$PROM_TAG"
